### ISSUE TITLE
Google Sheets plugin cross domain problems

### ISSUE THREAD

**Issue by matthewrball** [cdmedia/simplestore#19]
The Google Sheets plugin is not working correctly when implemented. I would also suggest adding a few more details to the readme file about this plugin.

You mentioned that the problem seemed intermittent based on the spreadsheet being used and that it looked like some cross domain problems.

**Comment by cdmedia** [comment]
Looks like I was using a depreciated URL structure for accessing the product part of the sheet. This was causing cross domain errors too. I updated the calls to support new structure.
